# Generated by Django 3.2.8 on 2022-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Телефон')),
                ('date', models.CharField(max_length=100, verbose_name='Телефон')),
                ('time', models.CharField(max_length=100, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Сообщение')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ техники',
                'verbose_name_plural': 'Заказ техники',
            },
        ),
    ]
