# Generated by Django 3.2.8 on 2022-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_equipmentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentform',
            name='equipment',
            field=models.CharField(default=0, max_length=200, verbose_name='Техника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentform',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='equipmentform',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='equipmentform',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Время'),
        ),
    ]
