# Generated by Django 3.2.8 on 2022-02-18 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20220217_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес объекта')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'pdf', 'jpg', 'png', 'bmp'])], verbose_name='Проект')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заказ услуги',
                'verbose_name_plural': 'Заказ услуги',
            },
        ),
    ]
