# Generated by Django 3.2.8 on 2022-02-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_testformmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactsForm',
            new_name='ContactsFormModel',
        ),
    ]
