# Generated by Django 3.2.8 on 2022-02-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=10)),
                ('rotation', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('drilling_depth', models.CharField(blank=True, max_length=50)),
                ('winch_capacity', models.CharField(blank=True, max_length=50)),
                ('drilling_diameter', models.CharField(blank=True, max_length=50)),
                ('hole_diameter', models.CharField(blank=True, max_length=50)),
                ('torque', models.CharField(blank=True, max_length=50)),
                ('max_digging_depth', models.CharField(blank=True, max_length=50)),
                ('maximum_breakout_force_on_bucket', models.CharField(blank=True, max_length=50)),
                ('maximum_breakout_force_on_handle', models.CharField(blank=True, max_length=50)),
                ('max_torque', models.CharField(blank=True, max_length=50)),
                ('bucket_capacity', models.CharField(blank=True, max_length=50)),
                ('max_span', models.CharField(blank=True, max_length=50)),
                ('mass_of_equipment', models.CharField(blank=True, max_length=50)),
                ('installation_weight', models.CharField(blank=True, max_length=50)),
                ('hydraulic_motor_power', models.CharField(blank=True, max_length=50)),
                ('engine_power', models.CharField(blank=True, max_length=50)),
                ('drive_power', models.CharField(blank=True, max_length=50)),
                ('working_radius', models.CharField(blank=True, max_length=50)),
                ('pile_dimensions', models.CharField(blank=True, max_length=50)),
                ('excavator_compatibility', models.CharField(blank=True, max_length=50)),
                ('machine_angle', models.CharField(blank=True, max_length=50)),
                ('feed_force', models.CharField(blank=True, max_length=50)),
                ('nominal_drilling_depth', models.CharField(blank=True, max_length=50)),
                ('rotator_stroke', models.CharField(blank=True, max_length=50)),
                ('feeding_stroke', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('rotation_frequency', models.CharField(blank=True, max_length=50)),
                ('spindle_speed', models.CharField(blank=True, max_length=50)),
                ('longitudinal_horizontal_pitch', models.CharField(blank=True, max_length=50)),
                ('operating_weight', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('object', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('square', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ShemeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_full', models.CharField(blank=True, max_length=250, verbose_name='Название полное')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_full', models.TextField(blank=True, verbose_name='Описание полное')),
                ('image_preview', models.ImageField(upload_to='', verbose_name='Превью')),
                ('image_detail', models.ImageField(upload_to='', verbose_name='Детальная картинка')),
                ('types_header', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для дополнительных услуг')),
                ('types_text', models.TextField(blank=True, verbose_name='Текст для дополнительных услуг')),
                ('projects_header', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для проектов')),
                ('projects_text', models.TextField(blank=True, verbose_name='Текст для проектов')),
                ('equipment_header', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для техники')),
                ('equipment_text', models.TextField(blank=True, verbose_name='Текст для техники')),
                ('scheme_header', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для схемы')),
                ('scheme_text', models.TextField(blank=True, verbose_name='Текст для схемы')),
                ('scheme_text_bottom', models.TextField(blank=True, verbose_name='Текст для схемы внизу')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment', to='services.Equipment', verbose_name='Техника')),
                ('projects', models.ManyToManyField(blank=True, related_name='projects', to='services.Project', verbose_name='Проекты')),
                ('scheme_items', models.ManyToManyField(blank=True, related_name='scheme_items', to='services.ShemeItems', verbose_name='Элементы схемы')),
                ('types', models.ManyToManyField(blank=True, related_name='types', to='services.Type', verbose_name='Дополнительные услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='images', to='services.ProjectImage'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.equipmentprice'),
        ),
    ]
