# Generated by Django 3.2.8 on 2022-02-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='equipmentprice',
            options={'verbose_name': 'Тип цены', 'verbose_name_plural': 'Типы цены'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Картинка проекта', 'verbose_name_plural': 'Картинки проекта'},
        ),
        migrations.AlterModelOptions(
            name='shemeitems',
            options={'verbose_name': 'Элемент схемы', 'verbose_name_plural': 'Элементы схемы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_weight2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Эксплуатационная масса'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bucket_capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальный объем ковша'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Габаритные размеры'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='drilling_depth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Глубина бурения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='drilling_diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Диаметр бурения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='drive_power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность привода'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='engine_power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='excavator_compatibility',
            field=models.CharField(blank=True, max_length=50, verbose_name='Совместимость с экскаватором'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='feed_force',
            field=models.CharField(blank=True, max_length=50, verbose_name='Усилие подачи'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='feeding_stroke',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ход подачи'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hole_diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Диаметр отверстия'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hydraulic_motor_power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность гидромотора'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='installation_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Масса установки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='longitudinal_horizontal_pitch',
            field=models.CharField(blank=True, max_length=50, verbose_name='Шаг продольный/горизонтальный'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='machine_angle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Угол поворота машины'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mass_of_equipment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Масса техники'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='max_digging_depth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальная глубина копания'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='max_span',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальный размах'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='max_torque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальный крутящий момент'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maximum_breakout_force_on_bucket',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальное усилие отрыва на ковше'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maximum_breakout_force_on_handle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Максимальное усилие отрыва на рукояти'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='nominal_drilling_depth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Условная глубина бурения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operating_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рабочий вес'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pile_dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размеры сваи'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.equipmentprice', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rotation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вращение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rotation_frequency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Частота вращения'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rotator_stroke',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ход вращателя'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='spindle_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Частота вращения шпинделя'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='torque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Крутящий момент'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='winch_capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Грузоподъемность лебедки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='working_radius',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рабочий радиус'),
        ),
        migrations.AlterField(
            model_name='equipmentprice',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='images', to='services.ProjectImage', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='project',
            name='object',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='square',
            field=models.CharField(blank=True, max_length=50, verbose_name='Площадь объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='shemeitems',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shemeitems',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
