# Generated by Django 3.2.8 on 2022-02-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220204_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='services.project'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
