# Generated by Django 3.2.8 on 2022-02-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220204_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
                ('text_top', models.TextField()),
                ('text_bottom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('value', models.TextField(verbose_name='Текст')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='services.scheme', verbose_name='Пункт схемы')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentproperty',
            name='position',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheme_header',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheme_items',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheme_text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheme_text_bottom',
        ),
        migrations.RemoveField(
            model_name='service',
            name='types',
        ),
        migrations.AddField(
            model_name='type',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='services.service', verbose_name='Дополнительная услуга'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='services.project', verbose_name='Проект'),
        ),
        migrations.DeleteModel(
            name='ShemeItems',
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme', to='services.service', verbose_name='Схема'),
        ),
    ]
