# Generated by Django 3.2.8 on 2022-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220206_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectproperty',
            options={'verbose_name': 'Свойство проекта', 'verbose_name_plural': 'Свойства проекта'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='object',
        ),
        migrations.RemoveField(
            model_name='project',
            name='period',
        ),
        migrations.RemoveField(
            model_name='project',
            name='square',
        ),
        migrations.AlterField(
            model_name='equipmentproperty',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='projectproperty',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
