# Generated by Django 3.2.8 on 2022-02-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentproperty',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='services.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectproperty',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='services.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='services.service', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='schemeitem',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.scheme', verbose_name='Пункт схемы'),
        ),
        migrations.AlterField(
            model_name='type',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='services.service', verbose_name='Дополнительная услуга'),
        ),
    ]
