# Generated by Django 3.2.8 on 2022-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220211_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Сообщение')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
    ]
