# Generated by Django 3.2.8 on 2022-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20220215_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactsform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
