# Generated by Django 3.2.8 on 2022-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20220215_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsform',
            name='comment',
            field=models.TextField(default='0', verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
