# Generated by Django 3.2.8 on 2022-02-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20220216_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallbackForm',
        ),
        migrations.DeleteModel(
            name='ContactsForm',
        ),
    ]
