# Generated by Django 3.2.8 on 2022-03-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20220216_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство техники',
                'verbose_name_plural': 'Свойства техники',
            },
        ),
        migrations.AddField(
            model_name='equipmentproperty',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='services.equipmentpropertyname', verbose_name='Свойство'),
        ),
    ]
