# Generated by Django 3.2.8 on 2022-03-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20220312_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentproperty',
            name='title',
        ),
    ]
