# Generated by Django 3.2.8 on 2022-03-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_equipmentproperty_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentproperty',
            old_name='field',
            new_name='title',
        ),
    ]
