# Generated by Django 3.2.8 on 2022-03-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_rename_field_equipmentproperty_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство проектов',
                'verbose_name_plural': 'Свойства проектов',
            },
        ),
        migrations.RemoveField(
            model_name='projectproperty',
            name='title',
        ),
        migrations.AlterField(
            model_name='equipmentproperty',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.equipmentpropertyname', verbose_name='Свойство'),
        ),
    ]
