# Generated by Django 3.2.8 on 2022-03-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20220312_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproperty',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.projectpropertyname', verbose_name='Свойство'),
        ),
    ]
