# Generated by Django 4.0.4 on 2022-06-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_contact_alter_projectpropertyname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=0, max_length=200, verbose_name='Юридический и почтовый адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер тел./факс'),
            preserve_default=False,
        ),
    ]
