# Generated by Django 4.0.4 on 2022-06-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_contact_address_contact_email_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
